server:
  port: 16666

hbaseconf:
  hbase_zk_quorum: "172.18.9.1"
  zk_znode_parent: "/hyperbase1"
  hbase_zk_property_client_port: "2181"
  hbase_rpc_timeout: 5000
  hbase_client_retries_number: 3

avater:
  hbase_zk_quorum: "172.18.9.1"
  zk_znode_parent: "/hyperbase1"
  hbase_zk_property_client_port: "2181"
  hbase_rpc_timeout: 5000
  hbase_client_retries_number: 3